#!/usr/bin/env python3
"""Amalgamate AxiomTrace core+frontend+port into a single header file."""

import re
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent / "baremetal"
OUT = ROOT.parent / "axiomtrace_amalgamated.h"

FILES = [
    ROOT / "include" / "axiom_static_assert.h",
    ROOT / "port" / "axiom_port.h",
    ROOT / "core" / "axiom_event.h",
    ROOT / "core" / "axiom_encode.h",
    ROOT / "core" / "axiom_crc.h",
    ROOT / "core" / "axiom_ring.h",
    ROOT / "core" / "axiom_timestamp.h",
    ROOT / "core" / "axiom_filter.h",
    ROOT / "frontend" / "axiom_frontend.h",
    ROOT / "backend" / "axiom_backend.h",
]

SOURCE_FILES = [
    ROOT / "port" / "axiom_port_generic.c",
    ROOT / "core" / "axiom_crc.c",
    ROOT / "core" / "axiom_ring.c",
    ROOT / "core" / "axiom_timestamp.c",
    ROOT / "core" / "axiom_filter.c",
    ROOT / "core" / "axiom_event.c",
    ROOT / "backend" / "axiom_backend.c",
]


def strip_includes(content: str, allowed_headers: set):
    """Remove #include lines for headers we are inlining."""
    lines = []
    for line in content.splitlines(keepends=True):
        m = re.match(r'\s*#include\s+"([^"]+)"', line)
        if m and m.group(1) in allowed_headers:
            continue
        lines.append(line)
    return ''.join(lines)


def run():
    allowed = {f.name for f in FILES}

    parts = []
    parts.append("/* ============================================================================\n")
    parts.append(" * AxiomTrace Single-File Amalgamated Library\n")
    parts.append(" * Auto-generated by tool/scripts/amalgamate.py\n")
    parts.append(" * ============================================================================ */\n\n")
    parts.append("#ifndef AXIOMTRACE_H\n")
    parts.append("#define AXIOMTRACE_H\n\n")
    parts.append("#include <stdint.h>\n")
    parts.append("#include <stddef.h>\n")
    parts.append("#include <stdbool.h>\n")
    parts.append("#include <string.h>\n\n")
    parts.append("#ifdef __cplusplus\n")
    parts.append("extern \"C\" {\n")
    parts.append("#endif\n\n")

    for f in FILES:
        parts.append(f"/* ===== {f.name} ===== */\n")
        content = f.read_text(encoding='utf-8')
        content = strip_includes(content, allowed)
        parts.append(content)
        parts.append("\n")

    for f in SOURCE_FILES:
        parts.append(f"/* ===== {f.name} ===== */\n")
        content = f.read_text(encoding='utf-8')
        content = strip_includes(content, allowed)
        parts.append(content)
        parts.append("\n")

    parts.append("#ifdef __cplusplus\n")
    parts.append("}\n")
    parts.append("#endif\n\n")
    parts.append("#endif /* AXIOMTRACE_H */\n")

    OUT.write_text(''.join(parts), encoding='utf-8')
    print(f"Generated {OUT} ({len(''.join(parts))} bytes)")


if __name__ == '__main__':
    run()
